/*
 * This file is generated by jOOQ.
*/
package br.com.rodrigocardoso.database.tables;


import br.com.rodrigocardoso.database.Indexes;
import br.com.rodrigocardoso.database.Keys;
import br.com.rodrigocardoso.database.Public;
import br.com.rodrigocardoso.database.tables.records.TarefasDiasRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TarefasDias extends TableImpl<TarefasDiasRecord> {

    private static final long serialVersionUID = 688029460;

    /**
     * The reference instance of <code>public.tarefas_dias</code>
     */
    public static final TarefasDias TAREFAS_DIAS = new TarefasDias();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TarefasDiasRecord> getRecordType() {
        return TarefasDiasRecord.class;
    }

    /**
     * The column <code>public.tarefas_dias.id</code>.
     */
    public final TableField<TarefasDiasRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('entidade_id_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.tarefas_dias.created</code>.
     */
    public final TableField<TarefasDiasRecord, Timestamp> CREATED = createField("created", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>public.tarefas_dias.modified</code>.
     */
    public final TableField<TarefasDiasRecord, Timestamp> MODIFIED = createField("modified", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>public.tarefas_dias.active</code>.
     */
    public final TableField<TarefasDiasRecord, Boolean> ACTIVE = createField("active", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false).defaultValue(org.jooq.impl.DSL.field("true", org.jooq.impl.SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.tarefas_dias.tarefas_id</code>.
     */
    public final TableField<TarefasDiasRecord, Integer> TAREFAS_ID = createField("tarefas_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.tarefas_dias.dias_id</code>.
     */
    public final TableField<TarefasDiasRecord, Integer> DIAS_ID = createField("dias_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>public.tarefas_dias</code> table reference
     */
    public TarefasDias() {
        this(DSL.name("tarefas_dias"), null);
    }

    /**
     * Create an aliased <code>public.tarefas_dias</code> table reference
     */
    public TarefasDias(String alias) {
        this(DSL.name(alias), TAREFAS_DIAS);
    }

    /**
     * Create an aliased <code>public.tarefas_dias</code> table reference
     */
    public TarefasDias(Name alias) {
        this(alias, TAREFAS_DIAS);
    }

    private TarefasDias(Name alias, Table<TarefasDiasRecord> aliased) {
        this(alias, aliased, null);
    }

    private TarefasDias(Name alias, Table<TarefasDiasRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.TAREFAS_DIAS_ID_PK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<TarefasDiasRecord, Integer> getIdentity() {
        return Keys.IDENTITY_TAREFAS_DIAS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TarefasDiasRecord> getPrimaryKey() {
        return Keys.TAREFAS_DIAS_ID_PK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TarefasDiasRecord>> getKeys() {
        return Arrays.<UniqueKey<TarefasDiasRecord>>asList(Keys.TAREFAS_DIAS_ID_PK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<TarefasDiasRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<TarefasDiasRecord, ?>>asList(Keys.TAREFAS_DIAS__TAREFAS_DIAS_TAREFAS_ID_FK, Keys.TAREFAS_DIAS__TAREFAS_DIAS_DIAS_ID_FK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TarefasDias as(String alias) {
        return new TarefasDias(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TarefasDias as(Name alias) {
        return new TarefasDias(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TarefasDias rename(String name) {
        return new TarefasDias(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TarefasDias rename(Name name) {
        return new TarefasDias(name, null);
    }
}
