/*
 * This file is generated by jOOQ.
*/
package br.com.rodrigocardoso.database.tables.records;


import br.com.rodrigocardoso.database.tables.TarefasDias;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TarefasDiasRecord extends UpdatableRecordImpl<TarefasDiasRecord> implements Record6<Integer, Timestamp, Timestamp, Boolean, Integer, Integer> {

    private static final long serialVersionUID = 1959221083;

    /**
     * Setter for <code>public.tarefas_dias.id</code>.
     */
    public TarefasDiasRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.tarefas_dias.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.tarefas_dias.created</code>.
     */
    public TarefasDiasRecord setCreated(Timestamp value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.tarefas_dias.created</code>.
     */
    public Timestamp getCreated() {
        return (Timestamp) get(1);
    }

    /**
     * Setter for <code>public.tarefas_dias.modified</code>.
     */
    public TarefasDiasRecord setModified(Timestamp value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.tarefas_dias.modified</code>.
     */
    public Timestamp getModified() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>public.tarefas_dias.active</code>.
     */
    public TarefasDiasRecord setActive(Boolean value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.tarefas_dias.active</code>.
     */
    public Boolean getActive() {
        return (Boolean) get(3);
    }

    /**
     * Setter for <code>public.tarefas_dias.tarefas_id</code>.
     */
    public TarefasDiasRecord setTarefasId(Integer value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.tarefas_dias.tarefas_id</code>.
     */
    public Integer getTarefasId() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.tarefas_dias.dias_id</code>.
     */
    public TarefasDiasRecord setDiasId(Integer value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.tarefas_dias.dias_id</code>.
     */
    public Integer getDiasId() {
        return (Integer) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, Timestamp, Timestamp, Boolean, Integer, Integer> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, Timestamp, Timestamp, Boolean, Integer, Integer> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return TarefasDias.TAREFAS_DIAS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field2() {
        return TarefasDias.TAREFAS_DIAS.CREATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return TarefasDias.TAREFAS_DIAS.MODIFIED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field4() {
        return TarefasDias.TAREFAS_DIAS.ACTIVE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return TarefasDias.TAREFAS_DIAS.TAREFAS_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return TarefasDias.TAREFAS_DIAS.DIAS_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component2() {
        return getCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component3() {
        return getModified();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component4() {
        return getActive();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getTarefasId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getDiasId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value2() {
        return getCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getModified();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value4() {
        return getActive();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getTarefasId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getDiasId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TarefasDiasRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TarefasDiasRecord value2(Timestamp value) {
        setCreated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TarefasDiasRecord value3(Timestamp value) {
        setModified(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TarefasDiasRecord value4(Boolean value) {
        setActive(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TarefasDiasRecord value5(Integer value) {
        setTarefasId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TarefasDiasRecord value6(Integer value) {
        setDiasId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TarefasDiasRecord values(Integer value1, Timestamp value2, Timestamp value3, Boolean value4, Integer value5, Integer value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TarefasDiasRecord
     */
    public TarefasDiasRecord() {
        super(TarefasDias.TAREFAS_DIAS);
    }

    /**
     * Create a detached, initialised TarefasDiasRecord
     */
    public TarefasDiasRecord(Integer id, Timestamp created, Timestamp modified, Boolean active, Integer tarefasId, Integer diasId) {
        super(TarefasDias.TAREFAS_DIAS);

        set(0, id);
        set(1, created);
        set(2, modified);
        set(3, active);
        set(4, tarefasId);
        set(5, diasId);
    }
}
