/*
 * This file is generated by jOOQ.
*/
package br.com.rodrigocardoso.database.tables.records;


import br.com.rodrigocardoso.database.tables.Usuarios;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UsuariosRecord extends UpdatableRecordImpl<UsuariosRecord> implements Record6<Integer, Timestamp, Timestamp, Boolean, String, String> {

    private static final long serialVersionUID = -240637133;

    /**
     * Setter for <code>public.usuarios.id</code>.
     */
    public UsuariosRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.usuarios.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.usuarios.created</code>.
     */
    public UsuariosRecord setCreated(Timestamp value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.usuarios.created</code>.
     */
    public Timestamp getCreated() {
        return (Timestamp) get(1);
    }

    /**
     * Setter for <code>public.usuarios.modified</code>.
     */
    public UsuariosRecord setModified(Timestamp value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.usuarios.modified</code>.
     */
    public Timestamp getModified() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>public.usuarios.active</code>.
     */
    public UsuariosRecord setActive(Boolean value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.usuarios.active</code>.
     */
    public Boolean getActive() {
        return (Boolean) get(3);
    }

    /**
     * Setter for <code>public.usuarios.nome</code>.
     */
    public UsuariosRecord setNome(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.usuarios.nome</code>.
     */
    public String getNome() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.usuarios.celular</code>.
     */
    public UsuariosRecord setCelular(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.usuarios.celular</code>.
     */
    public String getCelular() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, Timestamp, Timestamp, Boolean, String, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, Timestamp, Timestamp, Boolean, String, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Usuarios.USUARIOS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field2() {
        return Usuarios.USUARIOS.CREATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return Usuarios.USUARIOS.MODIFIED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field4() {
        return Usuarios.USUARIOS.ACTIVE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Usuarios.USUARIOS.NOME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Usuarios.USUARIOS.CELULAR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component2() {
        return getCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component3() {
        return getModified();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component4() {
        return getActive();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getNome();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getCelular();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value2() {
        return getCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getModified();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value4() {
        return getActive();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getNome();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getCelular();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsuariosRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsuariosRecord value2(Timestamp value) {
        setCreated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsuariosRecord value3(Timestamp value) {
        setModified(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsuariosRecord value4(Boolean value) {
        setActive(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsuariosRecord value5(String value) {
        setNome(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsuariosRecord value6(String value) {
        setCelular(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsuariosRecord values(Integer value1, Timestamp value2, Timestamp value3, Boolean value4, String value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UsuariosRecord
     */
    public UsuariosRecord() {
        super(Usuarios.USUARIOS);
    }

    /**
     * Create a detached, initialised UsuariosRecord
     */
    public UsuariosRecord(Integer id, Timestamp created, Timestamp modified, Boolean active, String nome, String celular) {
        super(Usuarios.USUARIOS);

        set(0, id);
        set(1, created);
        set(2, modified);
        set(3, active);
        set(4, nome);
        set(5, celular);
    }
}
