/*
 * This file is generated by jOOQ.
*/
package br.com.rodrigocardoso.database;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>public.entidade_id_seq</code>
     */
    public static final Sequence<Long> ENTIDADE_ID_SEQ = new SequenceImpl<Long>("entidade_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.usuarios_id_seq</code>
     */
    public static final Sequence<Long> USUARIOS_ID_SEQ = new SequenceImpl<Long>("usuarios_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));
}
