/*
 * This file is generated by jOOQ.
*/
package br.com.rodrigocardoso.database;


import br.com.rodrigocardoso.database.tables.Entidade;
import br.com.rodrigocardoso.database.tables.Tarefas;
import br.com.rodrigocardoso.database.tables.Usuarios;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.entidade</code>.
     */
    public static final Entidade ENTIDADE = br.com.rodrigocardoso.database.tables.Entidade.ENTIDADE;

    /**
     * The table <code>public.tarefas</code>.
     */
    public static final Tarefas TAREFAS = br.com.rodrigocardoso.database.tables.Tarefas.TAREFAS;

    /**
     * The table <code>public.usuarios</code>.
     */
    public static final Usuarios USUARIOS = br.com.rodrigocardoso.database.tables.Usuarios.USUARIOS;
}
